version: 2.1

commands:
  install-prereq-aws-cli:
    steps:
     - run: apt update && apt install curl unzip groff less -y
  install-aws-cli:
    steps:
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip aws 
  install-eksctl:
    steps:
      - run: curl https://github.com/weaveworks/eksctl/releases/download/v0.132.0-rc.0/eksctl_Linux_amd64.tar.gz -o eksctl.tar.gz -L && tar xvzf eksctl.tar.gz && install eksctl /usr/local/bin/eksctl &&  rm eksctl.tar.gz && eksctl version
      - persist_to_workspace:
          root: workspace
          paths:
            - mybins/

  get-caller-identity:
    steps:
      - run: aws sts get-caller-identity
  eksctl_v:
    steps:
      - attach_workspace:
          at: mybins/
      - run: eksctl version
jobs:
  update-cluster:
    docker:
      - image: ubuntu:latest
    steps:
      - eksctl_v
  install-all:
    docker:
      - image: ubuntu:latest
    steps:
      - install-prereq-aws-cli
      - install-aws-cli
      - install-eksctl
      - get-caller-identity

workflows:
  cluster-management:
    jobs:
      - install-all:
          context: aws-access
      - update-cluster:
          context: aws-access
          requires: 
            - install-all
             
