version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0


commands:
  install-prereq-aws-cli:
    steps:
     - run: apt update && apt install curl unzip groff less -y


jobs:
  create-cluster:
    docker:
      - image: cimg/python:3.11.2
    steps:
#      - install-prereq-aws-cli
      - checkout
      - aws-eks/setup
#      - aws-eks/create-cluster:
#          config-file: vcc-eksctl-config.yaml
#      - create-deployment:
#          cluster-name: vcc-eksctl-24
#          requires:
#            - aws-eks/create-cluster
#      - aws-eks/delete-cluster:
#          config-file: vcc-eksctl-config.yaml

workflows:
  cluster-management:
    jobs:
      - create-cluster:
          name: create cluster
          context: aws-access
#          config-file: whatever
             
