version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  terraform: circleci/terraform@3.2.1
  kubernetes: circleci/kubernetes@1.3.1
  eks: circleci/aws-eks@2.2.0
commands:           
  set_env_vars:
    steps:
      - run:
          name: Set environment variables
          command: |
            echo 'export TF_VAR_environment_name=${CIRCLE_BRANCH}' >> $BASH_ENV 
  terraform_custom_init_script:
    steps:
      - run:
          name: init_script
          command: ENVIRONMENT_NAME=${CIRCLE_BRANCH} bash init.sh
          working_directory: terraform-eks
jobs:
  kubernetes_test:
    executor: aws-cli/default
    steps:
      - kubernetes/install
      - eks/install-aws-iam-authenticator
      - aws-cli/install
      - aws-cli/assume-role-with-web-identity:
          role-arn: arn:aws:iam::620241740192:role/CCI-OIDC-Role
          role-session-name: CCI-session
      - aws-cli/setup:
          aws-region: eu-west-1
      - eks/update-kubeconfig-with-authenticator:
          cluster-authentication-role-arn: arn:aws:iam::620241740192:role/CCI-OIDC-Role
          cluster-name: "vcc-cci-eks-cci-${CIRCLE_BRANCH}"
  eks-plan:
    executor: aws-cli/default
    steps: 
      - set_env_vars
      - checkout
      - aws-cli/install
      - aws-cli/assume-role-with-web-identity:
          role-arn: arn:aws:iam::620241740192:role/CCI-OIDC-Role
          role-session-name: CCI-session
      - run: aws sts get-caller-identity
      - terraform_custom_init_script
      - terraform/install
      - terraform/validate:
          path: terraform-eks
      - terraform/plan:
          path: terraform-eks
  eks-destroy:
    executor: aws-cli/default
    steps: 
      - set_env_vars
      - checkout
      - aws-cli/install
      - aws-cli/assume-role-with-web-identity:
          role-arn: arn:aws:iam::620241740192:role/CCI-OIDC-Role
          role-session-name: CCI-session
      - run: aws sts get-caller-identity
      - terraform_custom_init_script
      - terraform/install
      - terraform/validate:
          path: terraform-eks
      - terraform/destroy:
          path: terraform-eks        
  eks-apply:
    executor: aws-cli/default
    steps: 
      - set_env_vars
      - checkout
      - aws-cli/install
      - aws-cli/assume-role-with-web-identity:
          role-arn: arn:aws:iam::620241740192:role/CCI-OIDC-Role
          role-session-name: CCI-session
      - terraform_custom_init_script
      - terraform/install
      - terraform/validate:
          path: terraform-eks
      - terraform/plan:
          path: terraform-eks
      - terraform/apply:
          path: terraform-eks          

workflows:
  workflow1:
    jobs:
      - eks-plan:
          context: dummy
      - approve-apply:
          type: approval
          requires:
            - eks-plan
      - eks-apply:
          context: dummy
          requires: 
            - approve-apply
      - approve-destroy:
          type: approval
          requires:
            - eks-apply
      - eks-destroy:
          context: dummy
          requires: 
            - approve-destroy   
      - kubernetes_test:
          context: dummy         