version: 2.1
orbs:
  aws-eks: circleci/aws-eks@2.2.0


commands:
  install-prereq-aws-cli:
    steps:
     - run: apt update && apt install curl unzip groff less -y


jobs:
  install-eksctl:
    docker:
      - image: cimg/python:3.11.2
    steps:
#      - install-prereq-aws-cli
      - aws-eks/setup

workflows:
  cluster-management:
    jobs:
      - install-eksctl:
          name: install eksctl
 #         context: aws-access
#          config-file: whatever
             
