version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  docker: circleci/docker@2.2.0

jobs:
  all:
    executor: aws-cli/default
    steps: 
      - aws-cli/setup
      - run: aws sts get-caller-identity
      - docker/install-docker

workflows:
  workflow1:
    jobs:
      - all:
          context: aws-access
             
