version: 2.1

jobs:
  saluda:
    docker: 
      - image: ubuntu:latest
#    environment:
#      NOMBRE: miguel
    steps:
      - run: 
          environment:
            NOMBRE: jorge
          command: echo hola $NOMBRE
      - run: env

workflows:
  workflow1:
    jobs:
      - saluda
#          context: miprueba
             
