version: 2.1


commands:
  install-aws-cli:
    steps:
      - run: echo instalando

jobs:
  dependencies:
    docker: 
      - image: ubuntu:latest
    steps:
      - install-aws-cli

workflows:
  workflow1:
    jobs:
      - dependencies
             
