version: 2.1


commands:
  install-aws-cli:
    steps:
      - run: echoa instalando aws cli

jobs:
  install-dependencies:
    docker: 
      - image: ubuntu:latest
    steps:
      - install-aws-cli

workflows:
  workflow1:
    jobs:
      - install-dependencies
             
