version: 2.1

jobs:
  saluda:
    docker: 
      - image: ubuntu:latest
    environment:
      NOMBRE: miguel
    steps:
      - run: 
          command: echo hola $NOMBRE
          environment:
            NAME: jorge
      - run: env

workflows:
  workflow1:
    jobs:
      - saluda:
          context: miprueba
             
