version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  docker: circleci/docker@2.2.0

jobs:
  aws:
    executor: aws-cli/default
    steps: 
      - aws-cli/setup
      - run: aws sts get-caller-identity
  docker:
    executor: docker/docker
    steps:
      - docker/install-docker
      - docker/build:
          image: miimagen

workflows:
  workflow1:
    jobs:
      - aws:
          context: aws-access
      - docker:
          context: aws-access
             
