version: 2.1

commands:
  install-aws-cli:
    steps:
      - run: echo instalando aws cli
      - run: ls -la

jobs:
  install-dependencies:
    docker: 
      - image: ubuntu:latest
    steps:
      - install-aws-cli
      - checkout

workflows:
  workflow1:
    jobs:
      - install-dependencies
             
