version: 2.1

commands:
  install-prereq:
    steps:
     - run: apt update && apt install curl unzip groff less -y
  install-aws-cli:
    steps:
      - run: curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip" && unzip awscliv2.zip && ./aws/install && rm -rf awscliv2.zip aws 
  get-caller-identity:
    steps:
      - run: aws sts get-caller-identity
jobs:
  install-all:
    docker:
      - image: ubuntu:latest
    steps:
      - install-prereq
      - install-aws-cli
      - get-caller-identity

workflows:
  workflow1:
    jobs:
      - install-all:
          context: aws-access
             
