version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5

jobs:
  all:
    executor: aws-cli/default
    steps: 
      - aws-cli/setup
      - run: aws sts get-caller-identity

workflows:
  workflow1:
    jobs:
      - all
          context: aws-access
             
