version: 2.1

command:
  install-prereq:
    steps:
     - run: apt update && apt install curl unzip groff less -y

jobs:
  install-all:
    docker:
      - image: ubuntu:latest
    steps:
      - install-prereq

workflows:
  workflow1:
    jobs:
      - install-all:
          context: aws-access
             
