version: 2.1

commands:
  install-aws-cli:
    steps:
      - run: echo instalando aws cli

jobs:
  install-dependencies:
    docker: 
      - image: ubuntu:latest
    steps:
      - install-aws-cli
      - checkout
      - run: find

workflows:
  workflow1:
    jobs:
      - install-dependencies
             
