version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.5
  terraform: circleci/terraform@3.2.1
jobs:
  aws:
    executor: aws-cli/default
    steps: 
      - checkout
      - aws-cli/install
      - aws-cli/assume-role-with-web-identity:
          role-arn: arn:aws:iam::620241740192:role/CCI-OIDC-Role
          role-session-name: CCI-session
      - run: aws sts get-caller-identity
      - run: 
          name: init_script
          command: bash init.sh
          working_directory: terraform-eks
      - terraform/fmt:
          path: terraform-eks
      - terraform/plan:
          path: terraform-eks

workflows:
  workflow1:
    jobs:
      - aws:
          context: dummy
